import {
  ArrowDown,
  Bell,
  ChevronDown,
  ChevronRight,
  Clock,
  Copy,
  CornerUpLeft,
  Gavel,
  Info,
  Inbox,
  KeyRound,
  Link,
  LockKeyhole,
  LogIn,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  Monitor,
  MonitorSmartphone,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Search,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Trash2,
  UserRound,
  UsersRound,
  X,
  ZoomIn,
  ZoomOut,
  createIcons,
} from "lucide";

const iconSet = {
  ArrowDown,
  Bell,
  ChevronDown,
  ChevronRight,
  Clock,
  Copy,
  CornerUpLeft,
  Gavel,
  Info,
  Inbox,
  KeyRound,
  Link,
  LockKeyhole,
  LogIn,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  Monitor,
  MonitorSmartphone,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Search,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Trash2,
  UserRound,
  UsersRound,
  X,
  ZoomIn,
  ZoomOut,
};

export function renderIcons(root: Element | Document | DocumentFragment = document) {
  createIcons({ icons: iconSet, root });
}

export function iconElement(name: string, className?: string) {
  const element = document.createElement("i");
  element.dataset.lucide = name;
  element.setAttribute("aria-hidden", "true");
  if (className) element.className = className;
  return element;
}
