import assert from "node:assert/strict";
import { SQL } from "bun";
import { chromium, type Page } from "playwright";

const base = Bun.env.DATABASE_URL ?? "postgres://localhost:5432/priv_chat";
const adminBase = Bun.env.ADMIN_DATABASE_URL ?? base;
const sql = new SQL(base);
const adminSql = new SQL(adminBase);
const schema = `history_test_${crypto.randomUUID().replaceAll("-", "")}`;
const adminSchema = `history_admin_test_${crypto.randomUUID().replaceAll("-", "")}`;
await sql.unsafe(`create schema ${schema}`);
await adminSql.unsafe(`create schema ${adminSchema}`);
const scoped = (base: string, schema: string) => { const url = new URL(base); url.searchParams.set("options", `-c search_path=${schema}`); return url.toString(); };
Bun.env.DATABASE_URL = scoped(base, schema);
Bun.env.ADMIN_DATABASE_URL = scoped(adminBase, adminSchema);
Bun.env.NODE_ENV = "test";
const { db, closeDatabase } = await import("../src/db/client");
const { closeAdminDatabase } = await import("../src/admin-db/client");
const { closeRedis } = await import("../src/redis/client");
const { migrate } = await import("../src/db/migrate");
const { migrateAdminDatabase } = await import("../src/admin-db/migrate");
const { createApp } = await import("../src/app");
const build = await Bun.build({ entrypoints: ["scripts/fixtures/history-recovery-browser.ts"], target: "browser" });
if (!build.success) throw new Error(build.logs.map(String).join("\n"));
const js = await build.outputs[0].text();
const app = createApp().get("/history-test", () => new Response('<script type="module" src="/history-test.js"></script>', { headers: { "content-type": "text/html" } }))
  .get("/history-test.js", () => new Response(js, { headers: { "content-type": "text/javascript" } }));
const browser = await chromium.launch();
try {
  await migrate();
  await migrateAdminDatabase();
  app.listen({ hostname: "127.0.0.1", port: 0 });
  const origin = `http://127.0.0.1:${app.server!.port}`;
  const oldDevice = await (await browser.newContext()).newPage();
  const newDevice = await (await browser.newContext()).newPage();
  const recoveredDevice = await (await browser.newContext()).newPage();
  const stranger = await (await browser.newContext()).newPage();
  const request = (page: Page, path: string, body?: unknown, method = body ? "POST" : "GET") => page.evaluate(async ({ path, body, method }) => {
    const response = await fetch(path, { method, credentials: "include", headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, body: await response.json() };
  }, { path, body, method });
  const accountPassword = "Account-password-for-history-test!";
  for (const page of [oldDevice, newDevice, recoveredDevice, stranger]) await page.goto(`${origin}/history-test`);
  const registration = await request(oldDevice, "/v1/auth/register", { username: "history_user", password: accountPassword, displayName: "History user" });
  assert.equal(registration.status, 201);
  assert.equal((await request(stranger, "/v1/auth/register", { username: "history_stranger", password: accountPassword, displayName: "Stranger" })).status, 201);
  for (const page of [newDevice, recoveredDevice]) assert.equal((await request(page, "/v1/auth/login", { username: "history_user", password: accountPassword })).status, 200);
  await oldDevice.evaluate(() => (window as any).historyTest.initialize());
  const seed = await oldDevice.evaluate(() => (window as any).historyTest.seed());
  const invitation = await request(oldDevice, `/v1/servers/${seed.serverId}/invites`, {});
  assert.equal((await request(stranger, `/v1/invites/${invitation.body.invite.token}/accept`, {})).status, 200);
  await stranger.evaluate(() => (window as any).historyTest.initialize());
  const receivedHistory = await stranger.evaluate((id) => (window as any).historyTest.sendBatch(id), seed.conversationId);
  await oldDevice.evaluate(() => (window as any).historyTest.sync());
  assert.equal((await oldDevice.evaluate((message) => (window as any).historyTest.decryptMessage(message), receivedHistory[0])).content.body, "received older message 0", "Original device really holds keys for received history, not just cached plaintext");
  const recoveryKey = await oldDevice.evaluate(() => (window as any).historyTest.enable());
  await oldDevice.evaluate(() => (window as any).historyTest.backup());
  const oldDeviceId = await oldDevice.evaluate(() => (window as any).historyTest.initialize());
  assert.equal((await request(stranger, "/v1/crypto/history/backup")).body.backup, null);
  const newDeviceId = await newDevice.evaluate(() => (window as any).historyTest.initialize());
  await assert.rejects(newDevice.evaluate((seed) => (window as any).historyTest.decrypt(seed.conversationId, seed.encrypted), seed));
  const pairing = await newDevice.evaluate(() => (window as any).historyTest.request());
  assert.equal(pairing.deviceId, newDeviceId);
  assert.equal((await request(stranger, `/v1/crypto/history/transfers/${pairing.id}`)).status, 404);
  assert.equal(await newDevice.evaluate((pairing) => (window as any).historyTest.finish(pairing), pairing), null);
  await assert.rejects(oldDevice.evaluate((pairing) => (window as any).historyTest.approve({ ...pairing, secret: "A".repeat(43) }), pairing));
  await oldDevice.evaluate((pairing) => (window as any).historyTest.approve(pairing), pairing);
  const [{ encrypted_payload }] = await db`select encrypted_payload from history_device_transfers where id = ${pairing.id}`;
  assert.ok(!encrypted_payload.includes("private history fixture"));
  await newDevice.evaluate((pairing) => (window as any).historyTest.finish(pairing), pairing);
  const restored = await newDevice.evaluate((seed) => (window as any).historyTest.decrypt(seed.conversationId, seed.encrypted), seed);
  assert.equal(restored.name, "private history fixture");
  // Exercise the real UI, keeping chat open while a second tab imports keys.
  const uiContext = await browser.newContext();
  // Optionally verify the separately built desktop frontend against the real
  // backend, without changing its API/crypto code or persisting test plaintext.
  const frontendAssets = Bun.env.HISTORY_RECOVERY_FRONTEND_ASSETS;
  if (frontendAssets) {
    await uiContext.addInitScript((serverOrigin) => {
      (window as any).naigiDesktop = {
        getInfo: async () => ({ appVersion: "integration-test", serverVersion: null, serverOrigin }),
        getRealtimeUrl: async () => `${serverOrigin.replace(/^http/, "ws")}/v1/realtime`,
      };
    }, origin);
    await uiContext.route("**/*", async (route) => {
      const pathname = new URL(route.request().url()).pathname;
      const asset = pathname.startsWith("/channels/") || pathname === "/app" ? "chat.html"
        : pathname === "/settings" ? "settings.html" : pathname.slice(1);
      if (!asset || asset.includes("..") || pathname.startsWith("/v1/")) return route.continue();
      const file = Bun.file(`${frontendAssets}/${asset}`);
      if (!await file.exists()) return route.continue();
      await route.fulfill({ body: Buffer.from(await file.arrayBuffer()), contentType: file.type });
    });
  }
  const uiChat = await uiContext.newPage();
  await uiChat.goto(`${origin}/history-test`);
  assert.equal((await request(uiChat, "/v1/auth/login", { username: "history_user", password: accountPassword })).status, 200);
  await uiChat.evaluate(() => sessionStorage.setItem("priv-chat.local-passphrase", "ui-recovery-passphrase"));
  await uiChat.goto(`${origin}/channels/${seed.serverId}/${seed.channelId}`);
  await uiChat.locator(".unavailable-history").waitFor({ state: "visible" });
  const uiRecovery = await uiContext.newPage();
  await uiRecovery.goto(`${origin}/settings#recovery`);
  await uiRecovery.waitForFunction(() => !(document.getElementById("settings-name")?.textContent ?? "").includes("Loading"));
  await uiRecovery.locator("#recovery-local-passphrase").fill("ui-recovery-passphrase");
  await uiRecovery.getByText("Messages still locked? Check history keys", { exact: true }).click();
  await uiRecovery.locator("#history-diagnostics-link").fill(`${origin}/channels/${seed.serverId}/${seed.channelId}`);
  await uiRecovery.locator("#history-check-keys").click();
  await uiRecovery.locator("#history-diagnostics-result").filter({ hasText: "0 readable" }).waitFor();
  await uiRecovery.locator("#history-request-device").click();
  await uiRecovery.waitForFunction(() => Boolean((document.getElementById("history-pairing-link") as HTMLTextAreaElement)?.value));
  const uiLink = await uiRecovery.locator("#history-pairing-link").inputValue();
  const sourceRecovery = await oldDevice.context().newPage();
  await sourceRecovery.goto(`${origin}/settings#recovery`);
  await sourceRecovery.waitForFunction(() => !(document.getElementById("settings-name")?.textContent ?? "").includes("Loading"));
  await sourceRecovery.locator("#recovery-local-passphrase").fill("history-test-local-passphrase");
  await sourceRecovery.locator("#history-approval-link").fill(uiLink);
  await sourceRecovery.locator("#history-review-device").click();
  await sourceRecovery.getByText("Messages still locked? Check history keys", { exact: true }).click();
  await sourceRecovery.locator("#history-diagnostics-link").fill(`${origin}/channels/${seed.serverId}/${seed.channelId}`);
  await sourceRecovery.locator("#history-check-keys").click();
  await sourceRecovery.locator("#history-diagnostics-result").filter({ hasText: "50 readable" }).waitFor();
  await sourceRecovery.locator("#history-device-confirm").check();
  await sourceRecovery.locator("#history-approve-device").click();
  await sourceRecovery.locator("#history-recovery-status").filter({ hasText: "History transfer approved" }).waitFor();
  await uiRecovery.locator("#history-recovery-status").filter({ hasText: "Device approved" }).waitFor();
  await uiChat.bringToFront();
  await uiChat.getByText("received older message 0", { exact: true }).waitFor({ timeout: 10_000 });
  assert.equal(await uiChat.locator(".unavailable-history").count(), 0, "Received history also recovers through actual settings approval");
  await uiRecovery.locator("#history-check-keys").click();
  await uiRecovery.locator("#history-diagnostics-result").filter({ hasText: "50 readable" }).waitFor();
  await sourceRecovery.close();
  // Duplicate imports are valid, but must not claim to have unlocked more history.
  await uiRecovery.bringToFront();
  await uiRecovery.locator("#history-request-device").click();
  await uiRecovery.waitForFunction(() => Boolean((document.getElementById("history-pairing-link") as HTMLTextAreaElement)?.value));
  const duplicateLink = await uiRecovery.locator("#history-pairing-link").inputValue();
  const duplicateParts = new URL(duplicateLink).hash.replace("#approve-device=", "").split(".");
  await oldDevice.evaluate((pairing) => (window as any).historyTest.approve(pairing), { id: duplicateParts[0], deviceId: duplicateParts[1], secret: duplicateParts[2] });
  await uiRecovery.locator("#history-recovery-status").filter({ hasText: "no new or earlier keys" }).waitFor();
  assert.ok((await uiRecovery.locator("#history-recovery-status").textContent())?.includes("specific messages"));
  await uiChat.bringToFront();
  await uiChat.getByText("received older message 0", { exact: true }).waitFor();
  await uiContext.close();
  assert.equal((await request(newDevice, `/v1/crypto/history/transfers/${pairing.id}`)).status, 404, "transfer is consumed after import");
  await recoveredDevice.evaluate(() => (window as any).historyTest.initialize());
  await assert.rejects(recoveredDevice.evaluate(() => (window as any).historyTest.restore("NCR1-" + "A".repeat(43))));
  await recoveredDevice.evaluate((key) => (window as any).historyTest.restore(key), recoveryKey);
  assert.equal((await recoveredDevice.evaluate((seed) => (window as any).historyTest.decrypt(seed.conversationId, seed.encrypted), seed)).name, "private history fixture");
  const current = (await request(oldDevice, "/v1/crypto/history/backup")).body.backup;
  assert.equal((await request(oldDevice, "/v1/crypto/history/backup", { ...current, deviceId: crypto.randomUUID() }, "PUT")).status, 403);
  // Two writes based on the same snapshot cannot both succeed.
  const writes = await Promise.all([oldDevice, newDevice].map((page, index) => request(page, "/v1/crypto/history/backup", {
    ...current, deviceId: index === 0 ? oldDeviceId : newDeviceId,
  }, "PUT")));
  assert.deepEqual(writes.map((write) => write.status).sort(), [200, 409]);
  const added = await newDevice.evaluate(() => (window as any).historyTest.seed());
  await newDevice.evaluate(() => (window as any).historyTest.backup());
  await oldDevice.evaluate(() => (window as any).historyTest.backup());
  await recoveredDevice.evaluate((key) => (window as any).historyTest.restore(key), recoveryKey);
  assert.equal((await recoveredDevice.evaluate((seed) => (window as any).historyTest.decrypt(seed.conversationId, seed.encrypted), added)).name, "private history fixture", "merging preserves another device's keys");
  await recoveredDevice.evaluate(() => (window as any).historyTest.stop());
  await recoveredDevice.reload();
  await recoveredDevice.evaluate(() => (window as any).historyTest.initialize(false));
  assert.equal(await recoveredDevice.evaluate(() => (window as any).historyTest.hasBackup()), true, "Deferred initial key sync must still enable remembered automatic backup");
  const another = await newDevice.evaluate(() => (window as any).historyTest.request());
  await db`update history_device_transfers set expires_at = now() - interval '1 second' where id = ${another.id}`;
  assert.equal((await request(oldDevice, `/v1/crypto/history/transfers/${another.id}`)).status, 404);
  const revokedApproval = await newDevice.evaluate(() => (window as any).historyTest.request());
  await oldDevice.evaluate((pairing) => (window as any).historyTest.approve(pairing), revokedApproval);
  await db`update crypto_devices set revoked_at = now() where device_id = ${oldDeviceId}`;
  assert.equal((await request(newDevice, `/v1/crypto/history/transfers/${revokedApproval.id}`)).status, 404, "revoked approver cannot deliver queued keys");
  assert.equal((await request(oldDevice, "/v1/crypto/history/backup", { ...current, deviceId: oldDeviceId }, "PUT")).status, 403);
  const revokedRequester = await newDevice.evaluate(() => (window as any).historyTest.request());
  await db`update crypto_devices set revoked_at = now() where device_id = ${newDeviceId}`;
  assert.equal((await request(recoveredDevice, `/v1/crypto/history/transfers/${revokedRequester.id}`)).status, 404);
  for (const page of [oldDevice, newDevice, recoveredDevice]) await page.evaluate(() => (window as any).historyTest.stop());
  await recoveredDevice.goto(`${origin}/settings#recovery`);
  await recoveredDevice.waitForFunction(() => {
    const name = document.getElementById("settings-name")?.textContent;
    return Boolean(name && !name.includes("Loading"));
  });
  await recoveredDevice.locator("#history-request-device").waitFor({ state: "visible" });
  assert.equal(await recoveredDevice.locator(".history-recovery-card").count(), 2);
  await recoveredDevice.locator("#history-generate-key").click();
  await recoveredDevice.waitForFunction(() => /^NCR1-[A-Za-z0-9_-]{43}$/.test((document.getElementById("history-generated-key") as HTMLInputElement)?.value ?? ""));
  assert.match(await recoveredDevice.locator("#history-generated-key").inputValue(), /^NCR1-[A-Za-z0-9_-]{43}$/);
  assert.equal(await recoveredDevice.locator("#history-enable-backup").isDisabled(), true);
  await recoveredDevice.locator("#history-key-saved").check();
  assert.equal(await recoveredDevice.locator("#history-enable-backup").isEnabled(), true);
  assert.equal(await recoveredDevice.locator("#recovery-export-passphrase").isVisible(), false);
  await recoveredDevice.getByText("Manual file backup and import", { exact: true }).click();
  assert.equal(await recoveredDevice.locator("#recovery-export-passphrase").isVisible(), true);
  await recoveredDevice.locator('a[href="#accessibility"]').click();
  await recoveredDevice.locator("#app-scale").waitFor({ state: "visible" });
  assert.equal(await recoveredDevice.locator("#app-auto-load-media").isVisible(), false);
  assert.equal(await recoveredDevice.locator("#app-notification-mode").isVisible(), false);
  await recoveredDevice.locator("#app-scale").evaluate((element) => {
    (element as HTMLInputElement).value = "125";
    element.dispatchEvent(new Event("input", { bubbles: true }));
  });
  const leaveDialog = recoveredDevice.locator(".app-preferences-leave-dialog");
  await recoveredDevice.locator('a[href="#chat-media"]').click();
  await leaveDialog.getByRole("button", { name: "Stay here" }).click();
  assert.equal(new URL(recoveredDevice.url()).hash, "#accessibility");
  assert.equal(await recoveredDevice.locator("#app-scale").inputValue(), "125", "Stay preserves the draft");
  await recoveredDevice.locator('a[href="#chat-media"]').click();
  await leaveDialog.getByRole("button", { name: "Save changes" }).click();
  await recoveredDevice.locator("#app-auto-load-media").waitFor({ state: "visible" });
  assert.equal(await recoveredDevice.locator("#app-scale").inputValue(), "125", "Save persists preferences before changing categories");
  const savedMedia = await recoveredDevice.locator("#app-auto-load-media").isChecked();
  await recoveredDevice.locator("#app-auto-load-media").setChecked(!savedMedia);
  await recoveredDevice.locator('a[href="#notifications"]').click();
  await leaveDialog.getByRole("button", { name: "Discard changes" }).click();
  await recoveredDevice.locator("#app-notification-mode").waitFor({ state: "visible" });
  assert.equal(await recoveredDevice.locator("#app-auto-load-media").isChecked(), savedMedia, "Discard restores the saved draft");
  await recoveredDevice.locator("#app-sounds").click();
  await recoveredDevice.keyboard.press("Escape");
  await leaveDialog.getByRole("button", { name: "Stay here" }).click();
  assert.equal(new URL(recoveredDevice.url()).hash, "#notifications", "Escape respects unsaved changes");
  await recoveredDevice.evaluate(() => { window.location.hash = "#appearance"; });
  await leaveDialog.getByRole("button", { name: "Stay here" }).click();
  await recoveredDevice.waitForURL((url) => url.hash === "#notifications");
  assert.equal(new URL(recoveredDevice.url()).hash, "#notifications", "Direct hash navigation respects unsaved changes");
  await recoveredDevice.locator(".settings-close-button").click();
  await leaveDialog.getByRole("button", { name: "Discard changes" }).click();
  await recoveredDevice.waitForURL((url) => url.pathname !== "/settings");
  await recoveredDevice.goto(`${origin}/settings#app`);
  await recoveredDevice.locator("#theme-preset-cards").waitFor({ state: "visible" });
  assert.equal(await recoveredDevice.locator("#settings-page-title").textContent(), "Appearance", "Legacy app links open Appearance");
  assert.equal(await recoveredDevice.locator("#app-scale").isVisible(), false);
  await recoveredDevice.goto(`${origin}/history-test`);
  await recoveredDevice.goto(`${origin}/settings#approve-device=${revokedRequester.id}.${revokedRequester.deviceId}.${revokedRequester.secret}`);
  await recoveredDevice.locator("#history-review-device").waitFor({ state: "visible" });
  assert.equal(new URL(recoveredDevice.url()).hash, "#recovery", "approval secret is removed from the address bar");
  await recoveredDevice.waitForFunction(() => Boolean((document.getElementById("history-approval-link") as HTMLInputElement)?.value));
  assert.ok((await recoveredDevice.locator("#history-approval-link").inputValue()).includes(revokedRequester.secret));
  await recoveredDevice.evaluate(() => {
    const dialog = document.createElement("dialog");
    dialog.id = "escape-test-dialog";
    document.body.append(dialog);
    dialog.showModal();
  });
  await recoveredDevice.keyboard.press("Escape");
  await recoveredDevice.waitForFunction(() => !(document.getElementById("escape-test-dialog") as HTMLDialogElement).open);
  assert.equal(new URL(recoveredDevice.url()).pathname, "/settings", "Escape dismisses a dialog before leaving settings");
  await recoveredDevice.keyboard.press("Escape");
  await recoveredDevice.waitForURL((url) => url.pathname !== "/settings");
  assert.ok(["/app", "/unlock"].includes(new URL(recoveredDevice.url()).pathname), "Escape returns to chat without signing out");
  await recoveredDevice.goto(`${origin}/history-test`);
  await recoveredDevice.evaluate(() => sessionStorage.setItem("priv-chat.local-passphrase", "history-test-local-passphrase"));
  await recoveredDevice.goto(`${origin}/server-settings?server=${seed.serverId}`);
  await recoveredDevice.waitForFunction(() => (document.getElementById("server-name") as HTMLInputElement)?.value === "private history fixture", undefined, { timeout: 10_000 }).catch(async () => {
    throw new Error(`Space overview did not hydrate: ${new URL(recoveredDevice.url()).pathname}; ${await recoveredDevice.locator("#server-settings-status").textContent().catch(() => "no status")}`);
  });
  assert.equal(await recoveredDevice.locator("#server-description").inputValue(), "Saved private description");
  assert.equal(await recoveredDevice.locator("#welcome-heading").inputValue(), "Welcome, team");
  assert.equal(await recoveredDevice.locator("#welcome-enabled").isChecked(), true);
  assert.equal(await recoveredDevice.locator(".settings-sidebar-user").count(), 0);
  assert.ok(await recoveredDevice.locator("#server-description").getAttribute("placeholder"));
  await recoveredDevice.locator("#server-name").fill("Updated private space");
  await recoveredDevice.locator('a[href="#rooms"]').click();
  await recoveredDevice.getByRole("dialog").getByRole("button", { name: "Stay here" }).click();
  assert.equal(await recoveredDevice.locator("#server-name").inputValue(), "Updated private space");
  await recoveredDevice.locator('a[href="#rooms"]').click();
  await recoveredDevice.getByRole("dialog").getByRole("button", { name: "Save changes" }).click();
  await recoveredDevice.locator("#rooms").waitFor({ state: "visible" });
  await recoveredDevice.locator('a[href="#overview"]').click();
  await recoveredDevice.locator("#server-name").fill("Discard this draft");
  await recoveredDevice.keyboard.press("Escape");
  await recoveredDevice.getByRole("dialog").getByRole("button", { name: "Stay here" }).click();
  assert.equal(new URL(recoveredDevice.url()).pathname, "/server-settings");
  await recoveredDevice.locator("#back-to-server").click();
  await recoveredDevice.getByRole("dialog").getByRole("button", { name: "Discard changes" }).click();
  await recoveredDevice.waitForURL((url) => url.pathname !== "/server-settings");
  const missingKeysPage = await (await browser.newContext()).newPage();
  await missingKeysPage.goto(`${origin}/history-test`);
  assert.equal((await request(missingKeysPage, "/v1/auth/login", { username: "history_user", password: accountPassword })).status, 200);
  await missingKeysPage.evaluate(() => sessionStorage.setItem("priv-chat.local-passphrase", "fresh-browser-passphrase"));
  await missingKeysPage.goto(`${origin}/server-settings?server=${seed.serverId}`);
  await missingKeysPage.locator("#server-settings-status").filter({ hasText: "Could not unlock" }).waitFor();
  assert.equal(await missingKeysPage.locator("#server-name").isDisabled(), true);
  assert.equal(await missingKeysPage.locator("#save-server-button").isDisabled(), true, "Missing keys cannot overwrite saved space metadata");
  await missingKeysPage.keyboard.press("Escape");
  await missingKeysPage.waitForURL((url) => url.pathname !== "/server-settings");
  console.log("History recovery E2E passed: missing-key baseline, trusted transfer, backup restore, wrong secrets, account isolation, CAS concurrency, multi-device merging, expiry, replay, and revocation.");
} finally {
  await browser.close();
  await app.stop(true).catch(() => undefined);
  await closeRedis();
  await closeDatabase();
  await closeAdminDatabase();
  await sql.unsafe(`drop schema if exists ${schema} cascade`);
  await adminSql.unsafe(`drop schema if exists ${adminSchema} cascade`);
  await sql.close();
  await adminSql.close();
}
